#!/bin/sh -e
#
# $Id$

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is intended to invoke java test classes that run against the DFC,

if [ "$JAVA_HOME" = "" ] ; then
        JAVA_HOME=/usr/lib/jvm/java-1.5.0-sun
fi

JAVALIBPATH="$JAVA_HOME"/jre/lib/i386/client:"$JAVA_HOME"/jre/lib/i386:"$JAVA_HOME"/lib/i386:/usr/lib

SERVERCLASSPATH=/usr/share/java/metacarta-core.jar:documentum-testing-package/metacarta-documentumconnector-test.jar
SERVERCLASSPATH="$SERVERCLASSPATH":documentum-testing-package/TTTools.jar:/usr/share/java/log4j-1.2.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/DmcRecords.jar:/usr/share/java/messageService.jar:/usr/share/java/messageArchive.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/All-MB.jar:/usr/share/java/XformsCommon.jar:/usr/share/java/bpmutil.jar:/usr/share/java/bsf.jar:/usr/share/java/castor-0.9.5.2.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ci.jar:/usr/share/java/collaboration.jar:/usr/share/java/commons-jxpath-1.1.jar:/usr/share/java/ctsTransform.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ctsTransformImpl.jar:/usr/share/java/dfc.jar:/usr/share/java/dfcbase.jar:/usr/share/java/subscription.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/workflow.jar:/usr/share/java/xalan.jar:/usr/share/java/xercesImpl.jar:/usr/share/java/xforms.jar:/usr/share/java/xtrim-api.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/documentum/config

export DOCUMENTUM=/etc/documentum

CLASSNAME=$1
shift
"$JAVA_HOME"/bin/java -Xmx512m -Xms32m -Djava.library.path="$JAVALIBPATH" -Djava.io.tmpdir=/common/metacarta/java-temp -classpath "$JAVA_HOME"/jre/lib/rt.jar:"$JAVA_HOME"/lib/tools.jar:"$SERVERCLASSPATH" "$CLASSNAME" "$@"
