#!/bin/bash -e

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.#
# IF YOU ARE READING THIS, YOU ARE VIOLATING YOUR LICENSE AGREEMENT.
#
# $Id$

# Check superuser status
if [ `id -u` != "0" ]; then
    echo "$0: This script must be run as root"
    exit 1
fi

POSTGRES_MAINTENANCE_D=/usr/lib/metacarta/postgres-maintenance.d

if [ -d $POSTGRES_MAINTENANCE_D ]; then
    if ( /usr/bin/dotlockfile -l -r 0 /var/run/metacarta/postgres-maintenance-in-progress.lock ) ; then
	trap "/usr/bin/dotlockfile -u /var/run/metacarta/postgres-maintenance-in-progress.lock" EXIT
	# Abort if crawler reset in progress
	if [ ! -d /var/run/metacarta/reset-crawler-in-progress ] ; then
		/bin/run-parts --verbose --exit-on-error $POSTGRES_MAINTENANCE_D >/var/log/metacarta/last_postgres_maintenance.log 2>&1
		echo "Postgresql maintenance completed"
	else
		echo "Crawler reset in progress - skipping"
	fi
    else
	echo "Postgresql maintenance already in progress - skipping"
    fi
fi
