#!/bin/bash -e

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.#
# IF YOU ARE READING THIS, YOU ARE VIOLATING YOUR LICENSE AGREEMENT.
# $Id$

# We leave autovacuum on now.

# only create the agents cluster if it doesn't already exist
if [ ! -d /common/postgres/agents ]; then
    pg_createcluster --encoding=UTF8 8.3 --datadir=/common/postgres/agents agents
    # Set up the shared memory parameters so that things are not blazingly slow
    # this test must correctly apply to both 2950v2, 2950v3, and the R710
    # Note that the actual shared memory allocation takes place on installation
    # of metacarta-admin-common
    if /usr/lib/metacarta/get_hardware_type | egrep -q "(2950|R710)"
    then
	edit_config --file /etc/postgresql/8.3/agents/postgresql.conf --key shared_buffers --create-key --make-it 1024MB
    else
	edit_config --file /etc/postgresql/8.3/agents/postgresql.conf --key shared_buffers --create-key --make-it 640MB
    fi

    # Set checkpoint segments to something better
    edit_config --file /etc/postgresql/8.3/agents/postgresql.conf --key checkpoint_segments --create-key --make-it 300

    # A higher max_fsm_pages will mean that vacuum may actually help
    edit_config --file /etc/postgresql/8.3/agents/postgresql.conf --key max_fsm_pages --create-key --make-it 2048000

    # Set maintenance_work_mem, for vacuum
    edit_config --file /etc/postgresql/8.3/agents/postgresql.conf --key maintenance_work_mem --create-key --make-it 2097151

    # Set work_mem, for sorting
    edit_config --file /etc/postgresql/8.3/agents/postgresql.conf --key work_mem --create-key --make-it 2MB

    # Enable TCP socket
    #edit_config --file /etc/postgresql/8.3/agents/postgresql.conf --key tcpip_socket --create-key --make-it true

    edit_config --file /etc/postgresql/8.3/agents/postgresql.conf --key max_connections --create-key --make-it 400

    # Increase checkpoint interval
    edit_config --file /etc/postgresql/8.3/agents/postgresql.conf --key checkpoint_timeout --create-key --make-it 900
    
    # Increase logging since we're somewhat experimental.
    edit_config --file /etc/postgresql/8.3/agents/postgresql.conf --key log_destination --create-key --make-it "'syslog'"
    edit_config --file /etc/postgresql/8.3/agents/postgresql.conf --key log_min_messages --create-key --make-it error
    edit_config --file /etc/postgresql/8.3/agents/postgresql.conf --key silent_mode --create-key --make-it true
    edit_config --file /etc/postgresql/8.3/agents/postgresql.conf --key log_connections --create-key --make-it false
    edit_config --file /etc/postgresql/8.3/agents/postgresql.conf --key datestyle --create-key --make-it "'ISO,European'"

    # Turn off autovacuum; we do our own vacuuming on a cron job
    edit_config --file /etc/postgresql/8.3/agents/postgresql.conf --key autovacuum --create-key --make-it off

    #see what this file really is, but it looks like it won't work with edit_config                                                            
    ed /etc/postgresql/8.3/agents/pg_hba.conf >/dev/null <<EOF
,s/md5/password/
w
q
EOF

    # This is to allow local psql to connect with user 'metacarta'
    ed /etc/postgresql/8.3/agents/pg_hba.conf > /dev/null <<EOF
,s/local   all         all                               ident sameuser/local   all         all                               password/
w
q
EOF
else
    # Tighten "trust" security to "password" everywhere; this is done because of the upgrade case where security was looser before
    ed /etc/postgresql/8.3/agents/pg_hba.conf > /dev/null <<EOF
,s/trust/password/
w
q
EOF
fi
