<?xml version="1.0" encoding="UTF-8"?>
<!--
 Licensed to the Apache Software Foundation (ASF) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 The ASF licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>org.apache.manifoldcf</groupId>
    <artifactId>mcf-framework</artifactId>
    <version>2.31</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>

  <artifactId>mcf-spring-boot-app</artifactId>
  <name>ManifoldCF - Framework - Spring Boot App</name>
  <packaging>jar</packaging>

  <dependencies>
    <!-- Provided dependencies by Spring Boot (Tomcat) -->
    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
      <version>${servlet-api.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>jakarta.servlet.jsp</groupId>
      <artifactId>jakarta.servlet.jsp-api</artifactId>
      <version>${jsp-api.version}</version>
      <scope>provided</scope>
    </dependency>

    <!-- Compile dependencies -->
    <dependency>
      <groupId>jakarta.transaction</groupId>
      <artifactId>jakarta.transaction-api</artifactId>
      <version>${jakarta.transaction-api.version}</version>
    </dependency>
    <dependency>
      <groupId>jakarta.annotation</groupId>
      <artifactId>jakarta.annotation-api</artifactId>
      <version>2.1.1</version>
    </dependency>
    
    <!-- Spring Boot Starter Web -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <!-- Spring Boot Starter for scheduling -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-quartz</artifactId>
    </dependency>

    <!-- ManifoldCF Core library -->
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>mcf-core</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- ManifoldCF Agents library -->
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>mcf-agents</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- ManifoldCF Pull Agent library -->
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>mcf-pull-agent</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- ManifoldCF Connector Common library -->
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>mcf-connector-common</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- ManifoldCF Servlets -->
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>mcf-api-servlet</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>mcf-authority-servlet</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- ManifoldCF Connectors -->
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>mcf-filesystem-connector</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>mcf-nulloutput-connector</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>mcf-nulltransformation-connector</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>mcf-nullauthority-connector</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- Database driver -->
    <dependency>
      <groupId>org.hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <version>${spring-boot.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
