#!/bin/bash -e

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.#
# IF YOU ARE READING THIS, YOU ARE VIOLATING YOUR LICENSE AGREEMENT.
#
# $Id$

# Get rid of the cluster created by the package
if [ -d /etc/postgresql/8.3/main ]; then
    pg_dropcluster --stop 8.3 main
fi

# Disable cron vacuuming provided by postgres installation
if grep -q "^2 " /etc/cron.d/postgresql-common ; then
    ed /etc/cron.d/postgresql-common <<EOF
,s/^2 /# 2 /
w
q
EOF
fi




