#!/bin/sh -e
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.#
# IF YOU ARE READING THIS, YOU ARE VIOLATING YOUR LICENSE AGREEMENT.
#
# $Id$

# Weekly postgresql maintenance for crawler
# Cycle services, and do a vacuum full

if ( /etc/init.d/metacarta-agents stop | grep -s -q "(killing)" ) ; then
    echo "Performing lock clean"
    # Needed to kill agents process, so clean all locks to clean up
    if [ -x /etc/init.d/tomcat5.5 ] ; then
        /etc/init.d/tomcat5.5 stop
    fi
    /usr/lib/metacarta/core-lockclean
    # This kills any vacuums etc already in the works
    if ! /etc/init.d/postgresql-8.3 stop ; then
	echo "Database server did not shut down cleanly; restarting anyway"
    fi
    /etc/init.d/postgresql-8.3 start
    if [ -x /etc/init.d/tomcat5.5 ] ; then
        /etc/init.d/tomcat5.5 start
    fi
    # Give postgres more-than-sufficient time to start up
    export PGPASSWORD="local_pg_passwd"
    STARTUP_ATTEMPTS_REMAINING=360
    echo -n "Waiting for postgresql to start: "
    while psql -U metacarta -c "SELECT * FROM jobs LIMIT 0;" metacarta 2>&1 | grep -s -q "the database system is starting up"; do
	STARTUP_ATTEMPTS_REMAINING=$(($STARTUP_ATTEMPTS_REMAINING - 1));
	if [ $STARTUP_ATTEMPTS_REMAINING -le 0 ]; then
	    echo "Aborting w/o VACUUM."
	    exit 100
	fi

	sleep 10
	echo -n "."
    done
    echo "started."
fi

# Now, do the schema-independent postgresql work
export PGPASSWORD="local_pg_passwd"
psql -U metacarta -c "VACUUM FULL VERBOSE;" metacarta
