#!/bin/sh -e
#
# $Id$

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This command file controls the metacarta agents framework.

# Check superuser status
if [ `id -u` != "0" ]; then
    echo "$0: This script must be run as root"
    exit 1
fi

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=filenetconnector-server
FULLNAME=metacarta-filenetconnector-server
DESC="MetaCarta FileNet Connector Server"
DAEMON=/usr/lib/metacarta/filenetconnector-server
JAVA_HOME=/usr/lib/jvm/java-1.5.0-sun
AGENTS_USER=tomcat55
PIDFILE="/var/run/metacarta/$NAME.pid"
LOGDIR=/var/log/metacarta/java-agents
LOGFILE="$LOGDIR/agents.log"
test -f $DAEMON || exit 0
export JAVA_HOME

case "$1" in
  start)

	echo -n "Starting $DESC using Java from $JAVA_HOME: "

	touch "$PIDFILE" "$LOGFILE" || true
	chown --dereference $AGENTS_USER "$PIDFILE" "$LOGDIR" \
	    "$LOGFILE" || true
	if start-stop-daemon --test --start --pidfile "$PIDFILE" \
		--user $AGENTS_USER --startas "$DAEMON" >/dev/null; then
		# -p preserves the environment (for $JAVA_HOME etc.)
		# -s is required because the login shell is /bin/false
		su -p -s /bin/sh $AGENTS_USER \
			-c "\"$DAEMON\" start" \
			>>"$LOGFILE" 2>&1
		echo "$FULLNAME."
	else
		echo "(already running)."
	fi
	;;
  stop)
	echo -n "Stopping $DESC: "
	if start-stop-daemon --test --start --pidfile "$PIDFILE" \
		--user $AGENTS_USER --startas "$DAEMON" >/dev/null; then
		echo "(not running)."
	else
		su -p $AGENTS_USER -c "\"$DAEMON\" stop" >/dev/null 2>&1 || true
		# Fallback to kill the JVM process in case stopping did not work
		sleep 10
		start-stop-daemon --stop --oknodo --quiet --pidfile "$PIDFILE" --user $AGENTS_USER
		rm -f "$PIDFILE"
		echo "$FULLNAME."
	fi
	;;
  restart|force-reload)
	$0 stop
	sleep 1
	$0 start
	;;
  *)
	echo "Usage: /etc/init.d/metacarta-filenetconnector-server {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0

