<!--
 Licensed to the Apache Software Foundation (ASF) under one or more
 contributor license agreements.  See the NOTICE file distributed with
 this work for additional information regarding copyright ownership.
 The ASF licenses this file to You under the Apache License, Version 2.0
 (the "License"); you may not use this file except in compliance with
 the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->

<project name="mongodb" default="all">

    <property environment="env"/>
    <condition property="mcf-dist" value="${env.MCFDISTPATH}">
        <isset property="env.MCFDISTPATH"/>
    </condition>
    <property name="abs-dist" location="../../dist"/>
    <condition property="mcf-dist" value="${abs-dist}">
        <not>
            <isset property="env.MCFDISTPATH"/>
        </not>
    </condition>

    <import file="${mcf-dist}/connector-build.xml"/>

    <target name="download-cleanup">
        <delete>
            <fileset dir="test-materials" excludes="README*.txt"/>
        </delete>
    </target>

    <!-- MongoDB sync driver (MongoDB 9.x compliant) -->
    <patternset id="mongodb-driver-jars">
        <include name="mongodb-driver-sync-*.jar"/>
        <include name="mongodb-driver-core-*.jar"/>
        <include name="bson-*.jar"/>
    </patternset>

    <path id="connector-classpath">
        <path refid="mcf-connector-build.connector-classpath"/>
        <fileset dir="../../lib">
            <patternset refid="mongodb-driver-jars"/>
        </fileset>
    </path>

    <target name="lib" depends="mcf-connector-build.lib,precompile-check" if="canBuild">
        <mkdir dir="dist/lib"/>
        <copy todir="dist/lib">
            <fileset dir="../../lib">
                <patternset refid="mongodb-driver-jars"/>
            </fileset>
        </copy>
    </target>

    <target name="deliver-connector" depends="mcf-connector-build.deliver-connector">
        <antcall target="general-add-output-connector">
            <param name="connector-label" value="MongoDB"/>
            <param name="connector-class"
                   value="org.apache.manifoldcf.agents.output.mongodboutput.MongodbOutputConnector"/>
        </antcall>
    </target>

    <!-- Test materials: Testcontainers is used to run MongoDB 9.0.2 as a Docker container during the tests -->
    <property name="testcontainers.version" value="2.0.5"/>
    <property name="docker-java.version" value="3.7.1"/>
    <property name="duct-tape.version" value="1.0.8"/>
    <property name="jna.version" value="5.10.0"/>
    <property name="commons-compress.version" value="1.28.0"/>
    <property name="jetbrains-annotations.version" value="17.0.0"/>
    <property name="jackson-annotations.version" value="2.21"/>

    <!-- Test materials come first so that the newer jars required by Testcontainers
         (e.g. jackson-annotations, commons-compress) take precedence over the older shared ones -->
    <path id="connector-test-classpath">
        <fileset dir="test-materials" includes="*.jar" erroronmissingdir="false"/>
        <path refid="mcf-connector-build.connector-test-classpath"/>
    </path>

    <target name="calculate-testcode-condition">
        <condition property="tests-present">
            <and>
                <available file="test-materials/testcontainers-${testcontainers.version}.jar"/>
                <available file="test-materials/testcontainers-mongodb-${testcontainers.version}.jar"/>
                <available file="test-materials/docker-java-api-${docker-java.version}.jar"/>
                <available file="test-materials/docker-java-transport-${docker-java.version}.jar"/>
                <available file="test-materials/docker-java-transport-zerodep-${docker-java.version}.jar"/>
                <available file="test-materials/duct-tape-${duct-tape.version}.jar"/>
                <available file="test-materials/jna-${jna.version}.jar"/>
                <available file="test-materials/commons-compress-${commons-compress.version}.jar"/>
                <available file="test-materials/annotations-${jetbrains-annotations.version}.jar"/>
                <available file="test-materials/jackson-annotations-${jackson-annotations.version}.jar"/>
            </and>
        </condition>
    </target>

    <target name="pretest-warn" depends="calculate-testcode-condition" unless="tests-present">
        <echo message="Need Testcontainers download in order to run tests - run ant make-deps (Docker is required to run MongoDB 9.0.2)"/>
    </target>

    <target name="download-dependencies">
        <property name="maven-repo" value="https://repo1.maven.org/maven2"/>
        <mkdir dir="test-materials"/>
        <get src="${maven-repo}/org/testcontainers/testcontainers/${testcontainers.version}/testcontainers-${testcontainers.version}.jar" dest="test-materials/testcontainers-${testcontainers.version}.jar"/>
        <get src="${maven-repo}/org/testcontainers/testcontainers-mongodb/${testcontainers.version}/testcontainers-mongodb-${testcontainers.version}.jar" dest="test-materials/testcontainers-mongodb-${testcontainers.version}.jar"/>
        <get src="${maven-repo}/com/github/docker-java/docker-java-api/${docker-java.version}/docker-java-api-${docker-java.version}.jar" dest="test-materials/docker-java-api-${docker-java.version}.jar"/>
        <get src="${maven-repo}/com/github/docker-java/docker-java-transport/${docker-java.version}/docker-java-transport-${docker-java.version}.jar" dest="test-materials/docker-java-transport-${docker-java.version}.jar"/>
        <get src="${maven-repo}/com/github/docker-java/docker-java-transport-zerodep/${docker-java.version}/docker-java-transport-zerodep-${docker-java.version}.jar" dest="test-materials/docker-java-transport-zerodep-${docker-java.version}.jar"/>
        <get src="${maven-repo}/org/rnorth/duct-tape/duct-tape/${duct-tape.version}/duct-tape-${duct-tape.version}.jar" dest="test-materials/duct-tape-${duct-tape.version}.jar"/>
        <get src="${maven-repo}/net/java/dev/jna/jna/${jna.version}/jna-${jna.version}.jar" dest="test-materials/jna-${jna.version}.jar"/>
        <get src="${maven-repo}/org/apache/commons/commons-compress/${commons-compress.version}/commons-compress-${commons-compress.version}.jar" dest="test-materials/commons-compress-${commons-compress.version}.jar"/>
        <get src="${maven-repo}/org/jetbrains/annotations/${jetbrains-annotations.version}/annotations-${jetbrains-annotations.version}.jar" dest="test-materials/annotations-${jetbrains-annotations.version}.jar"/>
        <get src="${maven-repo}/com/fasterxml/jackson/core/jackson-annotations/${jackson-annotations.version}/jackson-annotations-${jackson-annotations.version}.jar" dest="test-materials/jackson-annotations-${jackson-annotations.version}.jar"/>
    </target>

</project>
