#!/bin/sh -e
#
# $Id$

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ "$JAVA_HOME" = "" ] ; then
        JAVA_HOME=/usr/lib/jvm/java-1.5.0-sun
fi

JAVALIBPATH="$JAVA_HOME"/jre/lib/i386/client:"$JAVA_HOME"/jre/lib/i386:"$JAVA_HOME"/lib/i386:/usr/lib

SERVERCLASSPATH=/usr/share/java/metacarta-core.jar:filenet-testing-package/metacarta-filenetconnector-test.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/log4j-1.2.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-activation.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-antlr.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-builtin_serialization.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-core_services_client.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-jaas.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-Jace.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-jaxm.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-jaxrpc.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-jetty.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-runner.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-saaj.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-validator.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-wasp.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-wsdl_api.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-xercesImpl.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-xml-apis.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ibm-xmlParserAPIs.jar

CLASSNAME=$1
shift
"$JAVA_HOME"/bin/java -Xmx512m -Xms32m -Djava.library.path="$JAVALIBPATH" -Djava.io.tmpdir=/common/metacarta/java-temp -Dwasp.location=/var/lib/filenet/wasp -classpath "$JAVA_HOME"/jre/lib/rt.jar:"$JAVA_HOME"/lib/tools.jar:"$SERVERCLASSPATH" "$CLASSNAME" "$@"
