#!/bin/sh -e
#
# $Id$

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This command file applies and removes a cert file for the memex lib to use as
# identification, if needed.

# Check superuser status
if [ `id -u` != "0" ]; then
    echo "$0: This script must be run as root"
    exit 1
fi

MEMEX_SSL_FILE="/usr/lib/metacarta/java-defines/memex.cacert.path"
MEMEX_SSL_VALUE="/var/lib/metacarta/memexconnector-cert.pem"

case "$1" in
  "installcert")
	# There'd better be a second argument
	if [ "$2" == "" ]; then
	    echo "Usage: $0 installcert <cert_file>" >&2
	    exit 1
	fi
        if [ ! -e "$2" ]; then
	    echo "Usage: $0 installcert <cert_file>" >&2
	    exit 1
	fi
	cp "$2" $MEMEX_SSL_VALUE
	echo $MEMEX_SSL_VALUE >$MEMEX_SSL_FILE
	# Restart the important services
	/etc/init.d/tomcat5.5 restart
	/etc/init.d/metacarta-agents restart
	;;
  "removecert")
	# No second arg necessary; restore system to original form
	rm -f $MEMEX_SSL_FILE
	# Restart the services
	/etc/init.d/tomcat5.5 restart
	/etc/init.d/metacarta-agents restart
	# Blow away the cert file
	rm -f $MEMEX_SSL_VALUE
	;;
  "status")
	if [ -e $MEMEX_SSL_FILE ] ; then
		echo "Certificate installed"
	else
		echo "No certificate installed"
	fi
	;;
  *)
        echo "Usage: $0 {installcert|removecert|status}" >&2
	exit 1
	;;
esac

exit 0

