#!/bin/sh -e
#
# $Id$

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is provided to provide the actual actions of the start/stop script,
# running as tomcat55, in a manner similar to tomcat

case "$1" in
    start)
	rm -rf /var/log/metacarta/java-agents/documentumconnector-monitor.out
        mkfifo -m700 /var/log/metacarta/java-agents/documentumconnector-monitor.out
	/usr/sbin/rotatelogs /var/log/metacarta/java-agents/documentumconnector-monitor_out.log 10M >/dev/null </var/log/metacarta/java-agents/documentumconnector-monitor.out &
	/usr/lib/metacarta/documentumconnector-monitor-daemon >> /var/log/metacarta/java-agents/documentumconnector-monitor.out 2>&1 &
 
	echo "Process ID of spawned monitor process: $!"
	# This code is correct; the pid file is created by /etc/init.d/metacarta-documentumconnector-monitor, and just filled in here.
	if [ -w /var/run/metacarta/documentumconnector-monitor.pid ]; then
	    echo $! > /var/run/metacarta/documentumconnector-monitor.pid
	fi
	;;
    stop)
	if [ -e /var/run/metacarta/documentumconnector-monitor.pid ]; then
	    kill $(</var/run/metacarta/documentumconnector-monitor.pid)
	fi
	rm -rf /var/log/metacarta/java-agents/documentumconnector-monitor.out
	;;
    *)
	echo "Usage: $0 start|stop"
	exit 1
	;;
esac
exit 0
