#!/bin/sh -e
#
# $Id$

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is provided to provide the actual actions of the start/stop script,
# in a manner similar to tomcat

PORT=1099

if [ "$JAVA_HOME" = "" ] ; then
        JAVA_HOME=/usr/lib/jvm/java-1.5.0-sun
fi

JAVALIBPATH="$JAVA_HOME"/jre/lib/i386/client:"$JAVA_HOME"/jre/lib/i386:"$JAVA_HOME"/lib/i386:/usr/lib

SERVERCLASSPATH=/usr/share/java/metacarta-documentumconnector-registry.jar:/usr/share/java/metacarta-documentumconnector-ifc.jar:/usr/share/java/metacarta-documentumconnector-stub.jar

case "$1" in
    start)
	rm -rf /var/log/metacarta/java-agents/documentumconnector-rmiregistry.out
        mkfifo -m700 /var/log/metacarta/java-agents/documentumconnector-rmiregistry.out
	/usr/sbin/rotatelogs /var/log/metacarta/java-agents/documentumconnector-rmiregistry_out.log 10M >/dev/null </var/log/metacarta/java-agents/documentumconnector-rmiregistry.out &
	"$JAVA_HOME"/bin/java -Xmx32m -Xms32m -classpath "$JAVA_HOME"/jre/lib/rt.jar:"$JAVA_HOME"/lib/tools.jar:"$SERVERCLASSPATH" -Djava.library.path="$JAVALIBPATH" -Djava.io.tmpdir=/common/metacarta/java-temp com.metacarta.crawler.registry.DCTM.DCTM >> /var/log/metacarta/java-agents/documentumconnector-rmiregistry.out 2>&1 &
 
	echo "Process ID of spawned JVM: $!"
	# This code is correct; the pid file is created by /etc/init.d/metacarta-documentumconnector-rmiregistry, and just filled in here.
	if [ -w /var/run/metacarta/documentumconnector-rmiregistry.pid ]; then
	    echo $! > /var/run/metacarta/documentumconnector-rmiregistry.pid
	fi
	;;
    stop)
	if [ -e /var/run/metacarta/documentumconnector-rmiregistry.pid ]; then
	    kill $(</var/run/metacarta/documentumconnector-rmiregistry.pid)
	fi
	rm -rf /var/log/metacarta/java-agents/documentumconnector-rmiregistry.out
	;;
    *)
	echo "Usage: $0 start|stop"
	exit 1
	;;
esac
exit 0

