#!/bin/sh

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


if [ "x${1}" = "xclean" ] ; then
    rm -f aclocal.m4 stamp-h.in config.h.in configure config.cache
    find . -type f -path \*db/dist\* -prune -o -name Makefile.in -print0 | xargs -0 rm -f
    find config/* -name CVS -prune -o -print0 | xargs -0 rm -f
else
    set -x -e
    mkdir -p config
    aclocal-1.9 -I config
    automake-1.9 --foreign --add-missing
    autoconf
fi
