#!/bin/sh -e
#
# $Id$

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is provided to provide the actual actions of the start/stop script,
# in a manner similar to tomcat

PORT=1099

if [ "$JAVA_HOME" = "" ] ; then
        JAVA_HOME=/usr/lib/jvm/java-1.5.0-sun
fi

JAVALIBPATH="$JAVA_HOME"/jre/lib/i386/client:"$JAVA_HOME"/jre/lib/i386:"$JAVA_HOME"/lib/i386:/usr/lib

SERVERCLASSPATH=/usr/share/java/metacarta-documentumconnector-server.jar:/usr/share/java/metacarta-documentumconnector-ifc.jar:/usr/share/java/metacarta-documentumconnector-stub.jar:/usr/share/java/metacarta-documentumconnector-skel.jar:/usr/share/java/metacarta-documentumconnector-impl.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/TTTools.jar:/usr/share/java/log4j-1.2.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/DmcRecords.jar:/usr/share/java/messageService.jar:/usr/share/java/messageArchive.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/All-MB.jar:/usr/share/java/XformsCommon.jar:/usr/share/java/bpmutil.jar:/usr/share/java/bsf.jar:/usr/share/java/castor-0.9.5.2.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ci.jar:/usr/share/java/collaboration.jar:/usr/share/java/commons-jxpath-1.1.jar:/usr/share/java/ctsTransform.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/ctsTransformImpl.jar:/usr/share/java/dfc.jar:/usr/share/java/dfcbase.jar:/usr/share/java/subscription.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/java/workflow.jar:/usr/share/java/xalan.jar:/usr/share/java/xercesImpl.jar:/usr/share/java/xforms.jar:/usr/share/java/xtrim-api.jar
SERVERCLASSPATH="$SERVERCLASSPATH":/usr/share/documentum/config

case "$1" in
    start)
	rm -rf /var/log/metacarta/java-agents/documentumconnector-server.out
        mkfifo -m700 /var/log/metacarta/java-agents/documentumconnector-server.out
	/usr/sbin/rotatelogs /var/log/metacarta/java-agents/documentumconnector-server_out.log 10M >/dev/null </var/log/metacarta/java-agents/documentumconnector-server.out &
	export DOCUMENTUM=/etc/documentum
	( cd /var/log/documentum ; "$JAVA_HOME"/bin/java -Xmx512m -Xms32m -Djava.library.path="$JAVALIBPATH" -Djava.io.tmpdir=/common/metacarta/java-temp -classpath "$JAVA_HOME"/jre/lib/rt.jar:"$JAVA_HOME"/lib/tools.jar:"$SERVERCLASSPATH" com.metacarta.crawler.server.DCTM.DCTM >>/var/log/metacarta/java-agents/documentumconnector-server.out 2>&1 & )
 
	echo "Process ID of spawned JVM: $!"
	# This code is correct; the pid file is created by /etc/init.d/metacarta-documentumconnector-server, and just filled in here.
	if [ -w /var/run/metacarta/java-pids/documentumconnector-server.pid ]; then
	    echo $! > /var/run/metacarta/java-pids/documentumconnector-server.pid
	fi
	;;
    stop)
	if [ -e /var/run/metacarta/java-pids/documentumconnector-server.pid ]; then
	    kill $(</var/run/metacarta/java-pids/documentumconnector-server.pid)
	fi
	rm -rf /var/log/metacarta/java-agents/documentumconnector-server.out
	;;
    *)
	echo "Usage: $0 start|stop"
	exit 1
	;;
esac
exit 0

