#! /bin/sh
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.#
# $Id$
# This script adds a document into the current documentum docbase, using
# the credentials supplied.  It will overwrite the document if the same
# one already exists.

# Check user status
if [ `id -u` != `id -u tomcat55` ]; then
    echo "$0: This script must be run as tomcat55"
    exit 1
fi

/usr/lib/metacarta/executejava com.metacarta.crawler.connectors.livelink.GetConnectionInfo "$@"
