#! /bin/sh -e
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.#
# IF YOU ARE READING THIS, YOU ARE VIOLATING YOUR LICENSE AGREEMENT.
#
# $Id$
# This script configures the documentum wdk to point to the docbroker.
#
# Usage: setupdocumentum.sh <docbrokername> [<docbroker_port>]

# Check superuser status
if [ `id -u` != "0" ]; then
    echo "$0: You must run this script as root"
    exit 1
fi

if [ $# -ge 1 -a $# -le 2 ] ; then

# Stop tomcat and metacarta-agents
/etc/init.d/tomcat5.5 stop
/etc/init.d/metacarta-agents stop
/etc/init.d/metacarta-documentumconnector-server stop

  if [ $# -eq 1 ] ; then
DOCUMENTUM_PORT=1489
  else
DOCUMENTUM_PORT="$2"
  fi

/usr/bin/documentum-setbrokername "$1" "$DOCUMENTUM_PORT" 2000 

# Restart both tomcat and metacarta-agents
/etc/init.d/metacarta-documentumconnector-server start
/etc/init.d/tomcat5.5 start
/etc/init.d/metacarta-agents start

else

  echo "Usage: $0 <docbroker_host> [<docbroker_port>]"
  exit 1

fi
