#!/bin/sh -e
#
# $Id$

# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This command file sets and retrieves the NTLM configuration of Share Connector

# Check superuser status
if [ `id -u` != "0" ]; then
    echo "$0: This script must be run as root"
    exit 1
fi

LMCOMPATIBILITY_FILE="/usr/lib/metacarta/java-defines/jcifs.smb.lmCompatibility"
LMCOMPATIBILITY_NTLMV1_VALUE="0"
EXTENDEDSECURITY_FILE="/usr/lib/metacarta/java-defines/jcifs.smb.client.useExtendedSecurity"
EXTENDEDSECURITY_NTLMV1_VALUE="false"

case "$1" in
  "set")
	# Look at the second argument to determine what to do
	case "$2" in
	  "ntlmv1")
		echo $LMCOMPATIBILITY_NTLMV1_VALUE >$LMCOMPATIBILITY_FILE
		echo $EXTENDEDSECURITY_NTLMV1_VALUE >$EXTENDEDSECURITY_FILE
		# Restart the services that care about these settings
		/etc/init.d/tomcat5.5 restart
		/etc/init.d/metacarta-agents restart
		;;
	  "ntlmv2")
		rm -f $LMCOMPATIBILITY_FILE
		rm -f $EXTENDEDSECURITY_FILE
		# Restart the services that care about these settings
		/etc/init.d/tomcat5.5 restart
		/etc/init.d/metacarta-agents restart
		;;
	  *)
		echo "Usage: $0 set {ntlmv1|ntlmv2}" >&2
		exit 1
	esac
	;;
  "status")
	if [ -e $LMCOMPATIBILITY_FILE ] ; then
		echo "ntlmv1 mode"
	else
		echo "ntlmv2 mode"
	fi
	;;
  *)
	echo "Usage: $0 {set|status}" >&2
	exit 1
	;;
esac

exit 0

