#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: Publish Release Artifacts
run-name: ${{ github.actor }} is publishing release artifacts

on:
  workflow_dispatch:

jobs:
  deployReleaseMavenArtifacts:
    if: github.repository == 'apache/manifoldcf'
    name: "Deploy Apache ManifoldCF Snapshot"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Set up Java
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          cache: maven
          server-id: apache.releases.https
          server-username: NEXUS_USER
          server-password: NEXUS_PW
      - name: Ant Build
        run: ant make-core-deps make-deps image
      - name: Maven Build
        run: mvn clean install -B -DskipTests -DskipITs
      - name: Deploy
        run: mvn deploy -B -DskipTests -DskipITs -Dmaven.javadoc.skip=true
        env:
          NEXUS_USER: ${{ secrets.NEXUS_USER }}
          NEXUS_PW: ${{ secrets.NEXUS_PW }}
